import assert from "node:assert/strict"; import test from "node:test"; import { buildProviderTelemetryProjection, USAGE_POOL_SEMANTIC } from "../src/provider-telemetry.mjs";
const samples=[
 {model:{provider:"chat-provider",id:"chat-model"},attribution:{context_domain_id:"external:chat",context_domain_kind:"external-stateful",usage_pool:"chatgpt"},usage:{input_tokens:100,output_tokens:50,reasoning_tokens:5,cache_read_tokens:10,cache_write_tokens:0},activity:{calls:[{tool_call_id:"r1",tool_class:"read",target_path:"src/a.js"}]}},
 {model:{provider:"code-provider",id:"code-model"},attribution:{context_domain_id:"pi-native:code-provider",context_domain_kind:"pi-native",usage_pool:"codex"},usage:{input_tokens:300,output_tokens:150,reasoning_tokens:40,cache_read_tokens:20,cache_write_tokens:5},activity:{calls:[{tool_call_id:"e1",tool_class:"mutation",target_path:"src/b.js"},{tool_call_id:"b1",tool_class:"shell",target_path:null}]}}
];
const ops=[{operation_id:"r1",state:"TERMINAL",outcome:"KNOWN_SUCCESS"},{operation_id:"e1",state:"TERMINAL",outcome:"KNOWN_SUCCESS"},{operation_id:"b1",state:"TERMINAL",outcome:"KNOWN_FAILURE"}];
test("P6 projection exposes exact provider/model/domain/pool/token/tool primitives without quota claims",()=>{const p=buildProviderTelemetryProjection({metric_samples:samples,operation_outcomes:ops});assert.equal(p.model_calls,2);assert.equal(p.primary_tokens_observed,600);assert.equal(p.context_domains.length,2);assert.equal(p.models.length,2);assert.equal(p.usage_pools.length,2);const chat=p.usage_pools.find(x=>x.usage_pool==="chatgpt");assert.equal(chat.usage_pool_semantic,USAGE_POOL_SEMANTIC);assert.equal(chat.input_tokens,100);assert.equal(chat.output_tokens,50);assert.equal(chat.primary_token_share_percent,25);assert.equal(chat.reasoning_tokens,5);assert.equal(p.semantics.token_measurement,"captured_assistant_usage_fields_no_billing_inference");assert.equal(JSON.stringify(p).includes("quota_proof\":true"),false);});
test("P6 bounded operation outcomes and defensible file provenance stay exact",()=>{const p=buildProviderTelemetryProjection({metric_samples:samples,operation_outcomes:ops});const chat=p.tools_by_usage_pool.find(x=>x.usage_pool==="chatgpt");const code=p.tools_by_usage_pool.find(x=>x.usage_pool==="codex");assert.equal(chat.known_success,1);assert.equal(code.known_success,1);assert.equal(code.known_failure,1);assert.equal(code.mutation_calls,1);assert.equal(code.shell_calls,1);assert.deepEqual(p.provenance.successful_file_targets,["src/a.js","src/b.js"]);assert.equal(p.provenance.tests.status,"not_available_from_metric_samples");assert.equal(p.provenance.decisions.status,"not_available_from_metric_samples");assert.equal(p.work_mix.status,"not_computed");});
test("P6 incomplete usage is marked partial rather than invented",()=>{const p=buildProviderTelemetryProjection({metric_samples:[{model:{provider:"p",id:"m"},attribution:{context_domain_id:"d",context_domain_kind:"pi-native",usage_pool:"pool"},usage:{input_tokens:5},activity:{calls:[]}}]});assert.equal(p.usage_pools[0].usage_measurement_status,"partial_captured_fields");assert.equal(p.usage_pools[0].output_tokens,0);assert.equal(p.work_mix.status,"not_computed");});
